# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_host_hostadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostadmin',
            name='host',
        ),
        migrations.AddField(
            model_name='hostadmin',
            name='host',
            field=models.ManyToManyField(to='orm.Host'),
        ),
    ]
