# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20171028_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostadmin',
            name='host',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Hostadmin',
        ),
    ]
