# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orm', '0007_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('phone', models.IntegerField()),
                ('addr', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('publishDate', models.DateField()),
                ('authors', models.ManyToManyField(to='orm.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Pubname',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='pubname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.Pubname'),
        ),
        migrations.AddField(
            model_name='author',
            name='authorInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orm.AuthorInfo'),
        ),
    ]
