# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_auto_20171029_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authorInfo',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pubname',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorInfo',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Pubname',
        ),
    ]
